[package]
authors = ["layen-king <446495695@qq.com>"]
edition = "2018"
name = "leetcode"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4"
regex = "1.5.4"
rand = "0.8.5"
