[package]
name = "mime_types"
version = "0.1.0"
authors = ["layen-king <446495695@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.8.0"
